services:
  app:
    container_name: apexlog
    image: apexlog:latest
    volumes:
      - ./src:/var/www/html
    ports:
      - 8000:80
      - 5173:5173
    working_dir: /var/www/html
  db:
    container_name: apexlog-db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: apexlog
      MYSQL_USER: apexlog
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "8001:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
